# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _dSalmon
else:
    import _dSalmon

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class Distance32(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

# Register Distance32 in _dSalmon:
_dSalmon.Distance32_swigregister(Distance32)

class Distance64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr

# Register Distance64 in _dSalmon:
_dSalmon.Distance64_swigregister(Distance64)

class EuclideanDist32(Distance32):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dSalmon.EuclideanDist32_swiginit(self, _dSalmon.new_EuclideanDist32())
    __swig_destroy__ = _dSalmon.delete_EuclideanDist32

# Register EuclideanDist32 in _dSalmon:
_dSalmon.EuclideanDist32_swigregister(EuclideanDist32)

class EuclideanDist64(Distance64):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dSalmon.EuclideanDist64_swiginit(self, _dSalmon.new_EuclideanDist64())
    __swig_destroy__ = _dSalmon.delete_EuclideanDist64

# Register EuclideanDist64 in _dSalmon:
_dSalmon.EuclideanDist64_swigregister(EuclideanDist64)

class ManhattanDist32(Distance32):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dSalmon.ManhattanDist32_swiginit(self, _dSalmon.new_ManhattanDist32())
    __swig_destroy__ = _dSalmon.delete_ManhattanDist32

# Register ManhattanDist32 in _dSalmon:
_dSalmon.ManhattanDist32_swigregister(ManhattanDist32)

class ManhattanDist64(Distance64):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dSalmon.ManhattanDist64_swiginit(self, _dSalmon.new_ManhattanDist64())
    __swig_destroy__ = _dSalmon.delete_ManhattanDist64

# Register ManhattanDist64 in _dSalmon:
_dSalmon.ManhattanDist64_swigregister(ManhattanDist64)

class ChebyshevDist32(Distance32):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dSalmon.ChebyshevDist32_swiginit(self, _dSalmon.new_ChebyshevDist32())
    __swig_destroy__ = _dSalmon.delete_ChebyshevDist32

# Register ChebyshevDist32 in _dSalmon:
_dSalmon.ChebyshevDist32_swigregister(ChebyshevDist32)

class ChebyshevDist64(Distance64):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self):
        _dSalmon.ChebyshevDist64_swiginit(self, _dSalmon.new_ChebyshevDist64())
    __swig_destroy__ = _dSalmon.delete_ChebyshevDist64

# Register ChebyshevDist64 in _dSalmon:
_dSalmon.ChebyshevDist64_swigregister(ChebyshevDist64)

class MinkowskiDist32(Distance32):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, p):
        _dSalmon.MinkowskiDist32_swiginit(self, _dSalmon.new_MinkowskiDist32(p))
    __swig_destroy__ = _dSalmon.delete_MinkowskiDist32

# Register MinkowskiDist32 in _dSalmon:
_dSalmon.MinkowskiDist32_swigregister(MinkowskiDist32)

class MinkowskiDist64(Distance64):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, p):
        _dSalmon.MinkowskiDist64_swiginit(self, _dSalmon.new_MinkowskiDist64(p))
    __swig_destroy__ = _dSalmon.delete_MinkowskiDist64

# Register MinkowskiDist64 in _dSalmon:
_dSalmon.MinkowskiDist64_swigregister(MinkowskiDist64)

class SDOcluststream32(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed):
        _dSalmon.SDOcluststream32_swiginit(self, _dSalmon.new_SDOcluststream32(observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed))

    def fit(self, data, times):
        return _dSalmon.SDOcluststream32_fit(self, data, times)

    def fit_predict(self, data, labels, times):
        return _dSalmon.SDOcluststream32_fit_predict(self, data, labels, times)

    def observer_count(self):
        return _dSalmon.SDOcluststream32_observer_count(self)

    def get_observers(self, data, labels, observations, av_observations, time):
        return _dSalmon.SDOcluststream32_get_observers(self, data, labels, observations, av_observations, time)
    __swig_destroy__ = _dSalmon.delete_SDOcluststream32

# Register SDOcluststream32 in _dSalmon:
_dSalmon.SDOcluststream32_swigregister(SDOcluststream32)

class SDOcluststream64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed):
        _dSalmon.SDOcluststream64_swiginit(self, _dSalmon.new_SDOcluststream64(observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed))

    def fit(self, data, times):
        return _dSalmon.SDOcluststream64_fit(self, data, times)

    def fit_predict(self, data, labels, times):
        return _dSalmon.SDOcluststream64_fit_predict(self, data, labels, times)

    def observer_count(self):
        return _dSalmon.SDOcluststream64_observer_count(self)

    def get_observers(self, data, labels, observations, av_observations, time):
        return _dSalmon.SDOcluststream64_get_observers(self, data, labels, observations, av_observations, time)
    __swig_destroy__ = _dSalmon.delete_SDOcluststream64

# Register SDOcluststream64 in _dSalmon:
_dSalmon.SDOcluststream64_swigregister(SDOcluststream64)

class tpSDOsc32(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed):
        _dSalmon.tpSDOsc32_swiginit(self, _dSalmon.new_tpSDOsc32(observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed))

    def fit(self, data, times):
        return _dSalmon.tpSDOsc32_fit(self, data, times)

    def fit_predict(self, data, labels, times):
        return _dSalmon.tpSDOsc32_fit_predict(self, data, labels, times)

    def observer_count(self):
        return _dSalmon.tpSDOsc32_observer_count(self)

    def get_observers(self, data, labels, observations, av_observations, time):
        return _dSalmon.tpSDOsc32_get_observers(self, data, labels, observations, av_observations, time)
    __swig_destroy__ = _dSalmon.delete_tpSDOsc32

# Register tpSDOsc32 in _dSalmon:
_dSalmon.tpSDOsc32_swigregister(tpSDOsc32)

class tpSDOsc64(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed):
        _dSalmon.tpSDOsc64_swiginit(self, _dSalmon.new_tpSDOsc64(observer_cnt, T, idle_observers, neighbour_cnt, chi_min, chi_prop, zeta, e, freq_bins, max_freq, outlier_threshold, outlier_handling, perturb, random_sampling, distance, seed))

    def fit(self, data, times):
        return _dSalmon.tpSDOsc64_fit(self, data, times)

    def fit_predict(self, data, labels, times):
        return _dSalmon.tpSDOsc64_fit_predict(self, data, labels, times)

    def observer_count(self):
        return _dSalmon.tpSDOsc64_observer_count(self)

    def get_observers(self, data, labels, observations, av_observations, time):
        return _dSalmon.tpSDOsc64_get_observers(self, data, labels, observations, av_observations, time)
    __swig_destroy__ = _dSalmon.delete_tpSDOsc64

# Register tpSDOsc64 in _dSalmon:
_dSalmon.tpSDOsc64_swigregister(tpSDOsc64)



